@baseUrl = http://127.0.0.1:8000
@adminToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzY5OTUxNjI4LCJpYXQiOjE3Njk5NDk4Mjh9.9vEZDVN9ijOnrd2qVhYwvYsXREy6_JSbrmGgYlWj82I
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzY5OTUxNjI4LCJpYXQiOjE3Njk5NDk4Mjh9.9vEZDVN9ijOnrd2qVhYwvYsXREy6_JSbrmGgYlWj82I

###################################################
### GET ALL USERS (ADMIN ONLY)
###################################################
GET http://127.0.0.1:8000/users/1/me
Authorization: Bearer {{adminToken}}

###################################################
### AUTH – LOGIN ADMIN
###################################################
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@mail.com",
  "password": "123456"
}

###################################################
### AUTH – LOGIN USER
###################################################
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user@mail.com",
  "password": "user123"
}

###################################################
### CREATE USER (ADMIN ONLY)
###################################################
POST {{baseUrl}}/users
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "username": "user2",
  "email": "user2@mail.com",
  "password": "123456",
  "role": "user"
}

###################################################
### ACTIVATE / DEACTIVATE USER (ADMIN)
###################################################
PUT {{baseUrl}}/users/2/activate?active=true
Authorization: Bearer {{adminToken}}

###################################################
### USER UPDATE HIS OWN DATA
###################################################
PUT {{baseUrl}}/users/2
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "username": "user_updated",
  "email": "user_updated@mail.com"
}

###################################################
### USER TRY UPDATE ANOTHER USER (FORBIDDEN ❌)
###################################################
PUT {{baseUrl}}/users/1
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "username": "hacker"
}

###################################################
### ADMIN UPDATE ANY USER (ROLE / ACTIVE)
###################################################
PUT {{baseUrl}}/users/2/admin
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "role": "admin",
  "active": true
}

###################################################
### USER RESET HIS PASSWORD
###################################################
PUT {{baseUrl}}/users/2/reset-password
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "new_password": "newpassword123"
}

###################################################
### ADMIN RESET PASSWORD OF ANY USER
###################################################
PUT {{baseUrl}}/users/2/reset-password
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "new_password": "adminreset123"
}

###################################################
### LOGIN WITH NEW PASSWORD (CHECK)
###################################################
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user_updated@mail.com",
  "password": "newpassword123"
}


_______________________________________________________


###################################
### GET ALL DEVIS
###################################
GET {{baseUrl}}/devis/all
Authorization: Bearer {{adminToken}}

###################################
### CREATE DEVIS
###################################
POST {{baseUrl}}/devis/create
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "fk_client_id": 1,
  "fk_vehicule_id": 1,
  "fk_police_id": 1,
  "date_effet": "2026-02-01",
  "date_echeance": "2027-01-31",
  "prime_total": 4500
}

###################################
### UPDATE DEVIS
###################################
PUT {{baseUrl}}/devis/update/1
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "prime_total": 5200
}

###################################
### DELETE DEVIS (ADMIN)
###################################
DELETE {{baseUrl}}/devis/delete/1
Authorization: Bearer {{adminToken}}

###################################
### GET ALL QUITTANCES
###################################
GET {{baseUrl}}/quittance/all
Authorization: Bearer {{adminToken}}

###################################
### ENCAISSER QUITTANCE (PARTIEL)
###################################
POST {{baseUrl}}/quittance/encaisser/1
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "montant": 2000,
  "mode_paiement": "espece"
}

###################################
### ENCAISSER QUITTANCE (SOLDE)
###################################
POST {{baseUrl}}/quittance/encaisser/1
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "montant": 2500,
  "mode_paiement": "virement"
}

###################################
### DELETE QUITTANCE (ADMIN)
###################################
DELETE {{baseUrl}}/quittance/delete/1
Authorization: Bearer {{adminToken}}
